src/Entity/Enchere.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EnchereRepository")
 */
class Enchere
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\HistoriqueEncheres", mappedBy="enchere", orphanRemoval=true)
     */
    private $historiqueEncheres;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit", inversedBy="encheres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    public function __construct()
    {
        $this->historiqueEncheres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection|HistoriqueEncheres[]
     */
    public function getHistoriqueEncheres(): Collection
    {
        return $this->historiqueEncheres;
    }

    public function addHistoriqueEnchere(HistoriqueEncheres $historiqueEnchere): self
    {
        if (!$this->historiqueEncheres->contains($historiqueEnchere)) {
            $this->historiqueEncheres[] = $historiqueEnchere;
            $historiqueEnchere->setEnchere($this);
        }

        return $this;
    }

    public function removeHistoriqueEnchere(HistoriqueEncheres $historiqueEnchere): self
    {
        if ($this->historiqueEncheres->contains($historiqueEnchere)) {
            $this->historiqueEncheres->removeElement($historiqueEnchere);
            // set the owning side to null (unless already changed)
            if ($historiqueEnchere->getEnchere() === $this) {
                $historiqueEnchere->setEnchere(null);
            }
        }

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }
	
	public function __toString()
	{
		return $this->produit->getDescriptif();
	}
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
			<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
			<link href="css/base.css" rel="stylesheet">
		{% endblock %}
    </head>
    <body class="border-right border-left">
        {% block body %}{% endblock %}
        {% block javascripts %}
			<script type="text/javascript" src="//code.jquery.com/jquery-3.5.0.min.js"></script>
			<script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
		{% endblock %}
    </body>
</html>

templates/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Enchere VIP : Bienvenue{% endblock %}</title>
        {% block stylesheets %}
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
			<link href="css/index.css" rel="stylesheet">
		{% endblock %}
    </head>
	
        {% block body %}
		<div class="border-right border-left" id="container">
		<header>
		<nav class="navbar navbar-dark bg-dark">
			<a href="/"><img src="images/logo.png" title="Accueil" alt="Tahiti" class="img-logo"></a>
		{% if app.user %}
			<a href="{{ path('pack_jetons_index') }}" class="nav-link nav-item">ACHETER VOS JETONS</a>
			<div class="contenant">
				<img src="images/jeton.jpg" alt="jeton" class="img-jetons">
				<div class="texte_centrer">{{ nbJetons }}</div>
			</div>
			<span>
				<a href="{{ path('app_logout') }}" class="btn btn-outline-secondary" role="button">DECONNEXION</a><br>
				<span id="pseudo-name"><img src="images/logo_pseudo.png" alt="Utilisateur" width="25px"> {{ app.user.pseudo }}</span>
			</span>
		{% else %}
			<a href="{{ path('app_login') }}" class="btn btn-outline-primary" role="button">SE CONNECTER</a>
			<a href="{{ path('app_register') }}" class="btn btn-success" role="button">S'INSCRIRE</a>
		{% endif %}
		</nav>
		</header>
		
		<!-- le conteneur fenêtre -->
		<div class="marquee-rtl">
			<!-- le contenu défilant -->
			<div>Enchères en cours : Offre du moments 1 pack de 3 jetons acheter PLUS DE CHANCE DE GAGNER</div>
		</div>
		
		<section class="row">
		
		{% for enchere in encheres %}
            <div class="col-md-4 encheres">
					<div>
						<p id="temps-restant"><span id="temps_restant{{ enchere.id }}"></span></p>
						<img src="{{ asset(enchere.produit.image) }}" alt="{{ enchere.produit.descriptif }}" height="180px"><br>
						<span class="valeur-encheres">Valeur: {{ enchere.produit.prix }} €</span>
					</div>
					<span class="titre-encheres">{{ enchere.produit.descriptif }}</span><br>
					<form action="{{ path('utilisateur_placer') }}" method="POST">
						<input class="input-mise" type="number" required step="0.01" min="0.01" max="500" name="mise">
						<button class="btn btn-light btn-placer" name="id_enchere" value="{{ enchere.id }}">Placer une offre</button>
					</form>
			</div>
		{% endfor %}
		
		</section>
		
		<footer><h2>© 2020 Licence Pro ADMS</h2></footer>
	</div>
	
	{% block javascripts %}
	<script>
		function dateDiff(date1, date2){
			let diff = {}                           // Initialisation du retour
			let tmp = date2 - date1;
 
			tmp = Math.floor(tmp/1000);             // Nombre de secondes entre les 2 dates
			diff.sec = tmp % 60;                    // Extraction du nombre de secondes
 
			tmp = Math.floor((tmp-diff.sec)/60);    // Nombre de minutes (partie entière)
			diff.min = tmp % 60;                    // Extraction du nombre de minutes
 
			tmp = Math.floor((tmp-diff.min)/60);    // Nombre d'heures (entières)
			diff.hour = tmp % 24;                   // Extraction du nombre d'heures
     
			tmp = Math.floor((tmp-diff.hour)/24);   // Nombre de jours restants
			diff.day = tmp;
     
			return diff;
		}
		
		let lesEncheres = new Array({{encheres|length}});
		let indice = 0;
		{% for enchere in encheres %}
			lesEncheres[indice] = new Array();
			lesEncheres[indice].push("temps_restant{{ enchere.id }}"); //Créee les identifiants pour chaque enchère
			lesEncheres[indice].push("{{ enchere.dateFin|date('Y-m-d H:i:s') }}"); // Ajoute la date de fin de chaque enchère
			indice++;
		{% endfor %}
		
		start(); // Déclenche le compte à rebours
		function start() {
			for(let i=0; i<lesEncheres.length; i++) {
				lesEncheres[i].push(setInterval(function(){ compteur(i); }, 1000)); // On récupère la valeur de la minuterie définie pour 
																					// pouvoir arrêter le compteur quand le temps est écoulé
			}
		}
		
		function finish(idEnchere) {
			clearInterval(lesEncheres[idEnchere][2]); // Stop la minuterie
			document.getElementById(lesEncheres[idEnchere][0]).innerHTML = '<span id="enchere-fermee">Cette enchère est fermée<span>';
		}
		
		function compteur(idEnchere) {
			let date_actuelle = new Date();
			let date_fin = new Date(lesEncheres[idEnchere][1]);
			let diff = dateDiff(date_actuelle, date_fin);
			
			if(diff.sec < 0 ) finish(idEnchere);
			else {
				if(diff.day == 0)
					document.getElementById(lesEncheres[idEnchere][0]).innerHTML = 'Temps restant ' + diff.hour + 'h ' + diff.min + 'm ' + diff.sec + 's';
				else
					document.getElementById(lesEncheres[idEnchere][0]).innerHTML = 'Temps restant ' + diff.day + 'j ' + diff.hour + 'h ' + diff.min + 'm ' + diff.sec + 's';
			}
		}
	</script>
	{% endblock %}
	
	{% endblock %}
</html>